version: '3.7'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      # Se precisar configurar mais variáveis de ambiente, adicione aqui.
      # Exemplo:
      # MB_DB_TYPE: postgres
      # MB_DB_DBNAME: metabase
      # MB_DB_PORT: 5432
      # MB_DB_USER: username
      # MB_DB_PASS: password
      # MB_DB_HOST: db

volumes:
  metabase-data:
